name: API workflow
env:
  codecov_token: "2fe11169-9855-4e97-8c31-94d1252c1b0d"
  
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test python API
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    - name: Install requirements
      run: pip install -r api/requirements.txt
    - name: Run tests and collect coverage for calculator
      run: pytest --cov=api.calculator --cov-report=xml:calculator-coverage.xm
    - name: Run tests and collect coverage for smiles
      run: pytest --cov=api.smiles --cov-report=xml:smiles-coverage.xml
    - name: Upload coverage reports to Codecov with GitHub Action
      uses: codecov/codecov-action@v3

